# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      # Build for release
    - name: Build for release x86.NET with DepotDownloader Embedded
      run: dotnet publish -r win-x86 -c Release /p:PublishSingleFile=true /p:SelfContained=true /p:EnableCompressionInSingleFile=true /p:IncludeDepotDownloader=true
    - uses: actions/upload-artifact@v4
      with:
        name: Dropship.x86.Embedded.exe
        path: bin/Release/net8.0/win-x86/publish/Dropship.exe
    - name: Build for release x64.NET with DepotDownloader Embedded
      run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:SelfContained=true /p:EnableCompressionInSingleFile=true /p:IncludeDepotDownloader=true
    - uses: actions/upload-artifact@v4
      with:
        name: Dropship.x64.Embedded.exe
        path: bin/Release/net8.0/win-x64/publish/Dropship.exe
      
    # Ensure clean build for non-embedded version
    - name: Clean up previous build artifacts
      run: |
        rm -rf bin obj

    - name: Restore dependencies after cleaning
      run: dotnet restore

    - name: Build for release x86.NET
      run: dotnet publish -r win-x86 -c Release /p:PublishSingleFile=true /p:SelfContained=true /p:EnableCompressionInSingleFile=true /p:IncludeDepotDownloader=false
    - uses: actions/upload-artifact@v4
      with:
        name: Dropship.x86.exe
        path: bin/Release/net8.0/win-x86/publish/Dropship.exe
    - name: Build for release x64.NET with DepotDownloader Embedded
      run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:SelfContained=true /p:EnableCompressionInSingleFile=true /p:IncludeDepotDownloader=false
    - uses: actions/upload-artifact@v4
      with:
        name: Dropship.x64.exe
        path: bin/Release/net8.0/win-x64/publish/Dropship.exe
