# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      # Releases with .NET build-in
    - name: Build for release x86.NET
      run: dotnet publish -r win-x86 -c Release /p:PublishSingleFile=true /p:SelfContained=true /p:EnableCompressionInSingleFile=true
    - name: Build for release x64.NET
      run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:SelfContained=true /p:EnableCompressionInSingleFile=true
      # Releases without .NET
    - name: Build for release x86
      run: dotnet publish -r win-x86 -c Release /p:PublishSingleFile=true /p:SelfContained=false /p:EnableCompressionInSingleFile=true
    - name: Build for release x64
      run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:SelfContained=false /p:EnableCompressionInSingleFile=true
